name: CI

on:
    workflow_dispatch: # Can manually run from any branch
    push:
        branches:
            - main
    pull_request:

# Cancel previous jobs before starting this one. Works on pull_request event only due to use of head_ref.
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    php-tests:
        runs-on:
            group: 6792-mwcmanaged
            labels:
                - 6792-mwcmanaged
                - self-hosted
        strategy:
            matrix:
                php-version:
                    - '8.3'
                    - '8.2'
                    - '8.1'
                    - '8.0'
                    - '7.4'
            fail-fast: false

        steps:
            - name: Set up CICD Environment
              uses: gdcorp-partners/mwc-cicd-actions/cicd-setup@main

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Install Dependencies
              uses: gdcorp-partners/mwc-cicd-actions/run-composer@main
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Execute tests via PHPUnit
              uses: gdcorp-partners/mwc-cicd-actions/run-phpunit@main
              with:
                  php-version: ${{ matrix.php-version }}
                  command: '--order-by="random" --coverage-text'
